### PR TITLE
WebExtension port

### PR DESCRIPTION
**Pull request by mbid**
See the commit message of aaf3737.

### CODE REVIEW

**Comment by Riajyuu** [comment]
@mbid the author has not been active for a year and a half. I suggest you release another fork at your side onto AMO

**Comment by mbid** [comment]
Well that's unfortunate to hear. When you write *another* fork, are you suggesting there is already a fork of Dustman out there?

**Comment by Riajyuu** [comment]
@mbid As far as how I learn, no. But here is a suggestion: get a sign from AMO (this is easy and quick) and release your work on GitHub. Try not to host onto AMO (hard & slow from code review)

**Comment by mbid** [comment]
@Rictusempra Well according to the github activity panel, the original author was active in July this year. I'll wait a few days and then proceed as you suggested. If you want to try this version of the addon (and I don't really see why, since it's basically the same), you can just clone my fork and install via `about:debugging`.

**Comment by mbid** [comment]
So qzb didn't respond via either email or github. I wanted to attach a signed version of this fork, but couldn't because github seems to now allow attaching addons or something. Maybe I can upload the fork once ff57 arrives, because the old dustman won't work then. In the meantime, you can email if you can't wait to try out this version, or want to run it on android.

EDIT: Huh, so I could upload it now. Anyway, I couldn't upload an `.xpi` file, so maybe you'll have to rename the file and replace `.zip` with `.xpi`.
[dustman-2.0.1-an+fx.zip](https://github.com/qzb/dustman/files/1314524/dustman-2.0.1-an.fx.zip)

**Comment by qzb** [comment]
@mbid sorry for the silence. Honestly, I've switched to Chrome some time ago, so developing Dustman has no longer a priority for me. On top of that, I don't have much time lately, so I don't think that I will go back to work on this addon anytime soon. Since I'm not a fan of forks of abandoned projects, I would happily give you permissions to both this repo and addon's management panel, so you could just do your work, without waiting for me to answer for month or two. What do you say?

**Comment by mbid** [comment]
No problem. Sad to hear you've switched -- be sure to try out FF 57, it really feels much faster.
Anyway, I can take over maintainership of the addon. I don't really know how you can transfer ownership on mozilla's addon page. I have an account there though, also called "mbid".

**Pull request closed without merging**
